#include <iostream>
#include <string>
#include <vector>
#include <cmath>
#include <array>
#include <algorithm>
#include <map>
using namespace std;

enum PkmnTypes {BUG, DARK, DRAGON, ELECTRIC, FAIRY, FIGHTING, FIRE, FLYING, GHOST, GRASS, GROUND, ICE, NORMAL, POISON, PSYCHIC, ROCK, STEEL, WATER, NONE };
enum Category {PHYSICAL,SPECIAL,STATUS };
enum PkmnStatus{ SLEEP, FROZEN, PARALYZED, BURNED, POISONED, BADLY_POISONED, CONFUSED, ATTRACTED, HEALTHY};
enum Weather{ SUN, RAIN, SAND, HAIL, CLEAR};
enum TrainerClass{ ACE_TRAINER, AROMA_LADY, ATHLETE, BACKPACKER, BIKER, BIRD_KEEPER, BUG_MANIAC, CAMERAMAN, COOK, CHAMPION, COOL_BEAUTY, CUTE_MANIAC, ELITE_FOUR, FIREBREATHER, GENTLEMAN, GUITARIST, GYM_TRAINER, ROOKIE, RICH_BOY, FISHERMAN, BUG_CATCHER, GYM_LEADER, LASS };
